### ISSUE TITLE
Add functionality or remove Next and Prev buttons

### ISSUE THREAD

**Issue by addyng** [CSE-110-Group-13/warm-up#7]
# Add functionality or remove Next and Prev buttons

- The `prev` and `next` buttons don't currently do anything
    - Can either remove or add functionality to change the current month
    - May require some logic with linking it to the selector for eventListener
    - Could also be used to add support for different years

<img width="358" alt="image" src="https://github.com/CSE-110-Group-13/warm-up/assets/110417388/0d2aeab9-d465-4f90-82d2-e4c7469b9bb6">

**Comment by MaximPodgore** [comment]
Fixed in #13
