### ISSUE TITLE
Add styling to the calendar

### ISSUE THREAD

**Issue by addyng** [CSE-110-Group-13/warm-up#9]
# Add styling to the calendar

- No styling so far in terms of design/artistic approach
    - Maybe add some colors
    - Maybe change the color of a box/day if it has content inside it
         - This logic can be implemented by checking if the `<p>` is empty or not
    - Different font-families
  
- Add favicon?

<img width="890" alt="image" src="https://github.com/CSE-110-Group-13/warm-up/assets/110417388/28bd2458-0fd8-4a8e-90ed-72e0352408b7">

**Comment by Anibal-Alpizar** [comment]
Hi @addyng!

I'm going to take care of this issue
